name: Prison
authors: [TesDev91, SkepsonSk]
version: 1.0
depend: [WorldGuard]
main: pl.trollcraft.Main

commands:
  fly:
    description: Fly
  helpop:
    description: Helpop
  gamemode:
    description: Gamemode
    aliases: [gm]
  setwarp:
    description: SetWarp
  warp:
    description: Warp
  spawn:
    description: Spawn
  sellall:
    description: Sellall
  blastpick:
    description: BlastPick
  autosell:
    description: AutoSell
  guitest:
    description: GuiTest
  blasttest:
    description: BlastTest
  enchant:
    description: Enchant
  cell:
    description: Cell
    aliases: [cela]
  promote:
    description: Promote
    aliases: [awans]
  envoyadmin:
    description: Envoy Admin
    aliases: [enadm, envadm, envoyadm]
  envoy:
    description: Envoy
    aliases: [zrzut, zrz, env, en, przemyt, przem, prze]
  lootchest:
    description: Loot Chest
    aliases: [lc, lootc, lchest]
  debugcells:
    description: Debugging cells
  shop:
    description: Shop
    aliases: [sklep]
  kit:
    description: Kit
  boosteradmin:
    description: BoosterAdmin
    aliases: [boostera]
  booster:
    description: Booster
    aliases: [buster, bst]
  backpack:
    description: Backpack
  chat:
    description: Chat
  message:
    description: Message
    aliases: [msg, tell]
  broadcast:
    description: Broadcast
    aliases: [say, announce, annou, annc, say]
  lootchestkeys:
    description: Loot Chest keys.
    aliases: [lck]
  rename:
    description: Rename.
    aliases: [nazwa]